name: Deploy Backend to VPS

on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t ton-bot:latest .
      
      - name: Save and compress image
        run: |
          docker save ton-bot:latest | gzip > ton-bot.tar.gz
      
      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "ton-bot.tar.gz"
          target: "/root/backend/"
      
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/backend/
            docker load < ton-bot.tar.gz
            docker-compose down backend || true
            docker-compose up -d backend
            docker system prune -f